### PR TITLE
Include npmlist

### PR DESCRIPTION
**Pull request by hankchanocd**
Came across ```ipt``` a few days ago, and found my sever-months-old ```npmlist``` is a great fit to it. Would love to see it included to Awesome Workflow

### CODE REVIEW

**Comment by ruyadorno** [comment]
oh yeah 🎉that's awesome 😄 def a great fit!

thanks!

**Comment by ruyadorno** [comment]
oh yeah 🎉that's awesome 😄 def a great fit!

thanks!

**Comment by ruyadorno** [comment]
oh yeah 🎉that's awesome 😄 def a great fit!

thanks!

**Comment by ruyadorno** [comment]
oh yeah 🎉 def a great fit 😄

thanks!

**Comment by hankchanocd** [comment]
Glad you like it. :) ...(Github was glitching a lot yesterday lol)

**Pull request closed without merging**
